#! bin/bash

#Ask the user for a new path
read -p "Introduzca una ruta:" ruta
añadirpath() #Call the previous function
touch log.txt #Createa empty file 
cat |apt-get ruta>>log.txt # Copy the path in the log
export `date+%y%m%d`
echo log.txt #Show the file
